// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import (
	"database/sql"
)

type Market struct {
	Name                string
	BaseAsset           string
	QuoteAsset          string
	BaseAssetPrecision  int32
	QuoteAssetPrecision int32
	Tradable            bool
	StrategyType        int32
	BasePrice           float64
	QuotePrice          float64
	Active              bool
}

type MarketFee struct {
	ID            int32
	BaseAssetFee  int64
	QuoteAssetFee int64
	Type          string
	FkMarketName  string
}

type Swap struct {
	ID        string
	Message   []byte
	Timestamp int64
	Type      string
	FkTradeID string
}

type Trade struct {
	ID             string
	Type           int32
	FeeAsset       string
	FeeAmount      int64
	TraderPubkey   []byte
	StatusCode     int32
	StatusFailed   bool
	PsetBase64     string
	TxID           sql.NullString
	TxHex          string
	ExpiryTime     sql.NullInt64
	SettlementTime sql.NullInt64
	BasePrice      sql.NullFloat64
	QuotePrice     sql.NullFloat64
	FkMarketName   string
}

type TradeFee struct {
	ID            int32
	BaseAssetFee  int64
	QuoteAssetFee int64
	Type          string
	FkTradeID     string
}

type Transaction struct {
	ID          int32
	Type        string
	AccountName string
	TxID        string
	Timestamp   int64
}

type TransactionAssetAmount struct {
	ID              int32
	FkTransactionID int32
	Asset           string
	Amount          int64
}
