builds:
  # daemon

  ### Linux
  - id: "tdexd-linux-amd64"
    main: ./cmd/tdexd
    ldflags:
      - -s -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{.Date}}'
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    binary: tdexd-{{ .Os }}-{{ .Arch }}

  - id: "tdexd-linux-arm64"
    main: ./cmd/tdexd
    ldflags:
      - -s -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{.Date}}'
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    binary: tdexd-{{ .Os }}-{{ .Arch }}

  ### Darwin

  - id: "tdexd-darwin-amd64"
    main: ./cmd/tdexd
    ldflags:
      - -s -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{.Date}}'
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    binary: tdexd-{{ .Os }}-{{ .Arch }}

  - id: "tdexd-darwin-arm64"
    main: ./cmd/tdexd
    ldflags:
      - -s -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{.Date}}'
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/oa64-clang
      - CXX=/home/runner/work/osxcross/target/bin/oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    binary: tdexd-{{ .Os }}-{{ .Arch }}

  # CLI
  - id: "tdex"
    main: ./cmd/tdex
    ldflags:
      - -s -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{.Date}}'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: tdex-{{ .Os }}-{{ .Arch }}

  # tdexdconnect
  - id: "tdexdconnect"
    main: ./cmd/tdexdconnect
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: tdexdconnect-{{ .Os }}-{{ .Arch }}
## flag the semver v**.**.**-<tag>.* as pre-release on Github
release:
  prerelease: auto

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native

archives:
  - id: tdexd
    format: binary
    builds:
      - tdexd
    name_template: "tdexd-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

  - id: tdex
    format: binary
    builds:
      - tdex
    name_template: "tdex-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

  - id: tdexdconnect
    format: binary
    builds:
      - tdexdconnect
    name_template: "tdexdconnect-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

dockers:
  ###########################
  # tag latest & prerelease #
  ###########################

  #amd64
  - image_templates:
      - "ghcr.io/tdex-network/tdexd:{{ .Tag }}-amd64"
        # push always either release or prerelease with a docker tag with the semver only
    skip_push: "false"
    use: buildx
    dockerfile: goreleaser.Dockerfile
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    # Template of the docker build flags.
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=tdexd"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

    extra_files:
      - go.mod
      - go.sum
      - internal
      - config
      - pkg
      - cmd
      - api-spec

  # arm64
  - image_templates:
      - "ghcr.io/tdex-network/tdexd:{{ .Tag }}-arm64v8"
        # push always either release or prerelease with a docker tag with the semver only
    skip_push: "false"
    use: buildx
    dockerfile: goreleaser.Dockerfile
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: arm64
    # Template of the docker build flags.
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=tdexd"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

    extra_files:
      - go.mod
      - go.sum
      - internal
      - config
      - pkg
      - cmd
      - api-spec

docker_manifests:
  - name_template: ghcr.io/tdex-network/tdexd:{{ .Tag }}
    image_templates:
      - ghcr.io/tdex-network/tdexd:{{ .Tag }}-amd64
      - ghcr.io/tdex-network/tdexd:{{ .Tag }}-arm64v8
    skip_push: "false"

  - name_template: ghcr.io/tdex-network/tdexd:latest
    image_templates:
      - ghcr.io/tdex-network/tdexd:{{ .Tag }}-amd64
      - ghcr.io/tdex-network/tdexd:{{ .Tag }}-arm64v8
    skip_push: auto
