builds:
  # daemon
  - id: "tdexd-linux"
    main: ./cmd/tdexd
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    binary: tdexd-linux

  - id: "tdexd-darwin"
    main: ./cmd/tdexd
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    binary: tdexd-darwin

  # CLI
  - id: "tdex-linux"
    main: ./cmd/tdex
    ldflags:
      - -s -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{.Date}}'
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    binary: tdex-linux

  - id: "tdex-darwin"
    main: ./cmd/tdex
    ldflags:
      - -s -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{.Date}}'
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    binary: tdex-darwin

  # unlocker
  - id: "unlockerd"
    main: ./cmd/unlockerd
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    binary: unlockerd
## flag the semver v**.**.**-<tag>.* as pre-release on Github
release:
  prerelease: auto

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

archives:
  - id: tdexd
    format: binary
    builds:
      - tdexd-linux
      - tdexd-darwin
    name_template: "tdexd-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  - id: tdex
    format: binary
    builds:
      - tdex-linux
      - tdex-darwin
    name_template: "tdex-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  - id: unlockerd
    format: binary
    builds:
      - unlockerd-linux
      - unlockerd-darwin
    name_template: "unlockerd-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

dockers:
  # push always either release or prerelease with a docker tag with the semver only
  - skip_push: false
    dockerfile: Dockerfile
    # image templates
    image_templates:
      - "ghcr.io/tdex-network/tdexd:{{ .Tag }}"
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.Commit}}"
      - "--build-arg=DATE={{.Date}}"

    extra_files:
      - go.mod
      - go.sum
      - internal
      - config
      - pkg
      - cmd
      - api-spec
  # push only release with both a docker tag latest and one with the semver
  - skip_push: auto
    dockerfile: Dockerfile
    # image templates
    image_templates:
      - "ghcr.io/tdex-network/tdexd:latest"
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.Commit}}"
      - "--build-arg=DATE={{.Date}}"
    extra_files:
      - go.mod
      - go.sum
      - internal
      - config
      - pkg
      - cmd
      - api-spec
