name: Go

on:
  push:
    branches:
      - v1

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.2'

      - name: Run Nigiri
        uses: vulpemventures/nigiri-github-action@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run Intergration Tests
        run: make integrationtest
